import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';

import { createApolloClient } from '../lib/apolloClient';
import HeaderImage from '../src/components/HeaderImage';
import CoverImage from '../public/index-cover.jpeg';
import Card from '../src/components/common/surfaces/Card';
import HomePageContent from '../src/components/pages/home/HomePageContent';
import { Business } from '../src/components/pages/home/types';
import {
  BusinessPreviewsDocument,
  BusinessPreviewsQuery,
  BusinessPreviewsQueryVariables,
} from '../src/generated/graphql';

const Title = styled.p`
  margin: 0;
  font-size: 2rem;
  line-height: 3rem;
  color: ${({ theme }) => theme.colors.primary};
  z-index: 1;
`;

type Props = {
  newBusinesses?: Business[];
};

const Home: NextPage<Props> = (props) => {
  // const { data } = useTestQuery();
  // console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeaderImage height="30vh" backgroundImage={CoverImage}>
          <Title>Prague Life</Title>
        </HeaderImage>
        {props.newBusinesses && (
          <HomePageContent newBusinesses={props.newBusinesses} />
        )}
        <Card>Hi</Card>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const apolloClient = createApolloClient();
  try {
    const { data } = await apolloClient.query<
      BusinessPreviewsQuery,
      BusinessPreviewsQueryVariables
    >({
      query: BusinessPreviewsDocument,
      variables: { searchTerm: 'food' },
    });
    console.log(data);
    return {
      props: { newBusinesses: data.search?.business },
    };
  } catch (e) {
    console.log(e);
  }
  return {
    props: { newBusinesses: [] },
  };
};

export default Home;
